### ISSUE TITLE
Send the image from the esp32 to the backend

### ISSUE THREAD

**Issue by alexandrebedel** [alexandrebedel/SmartBin#14]
# Description

In order for us to detect the current trash in the bin, we need to take an image and send it to our backend which will detect the good type.

# Todo

- [x] Send the image with a post request
- [x] Move the servo motors
- [x] Make the good servo motor open from the given trash type
