### ISSUE TITLE
Create routes for trash api

### ISSUE THREAD

**Issue by bourdin-alix** [alexandrebedel/SmartBin#18]
# Description

Create routes to get data on Trash table

# Todo
- [x] Route GET ONE /api/trash/binId
- [x] Route GET ALL /api/trash
- [x] Create route POST /api/trash
