### ISSUE TITLE
Setup binId & QR code display on the m5

### ISSUE THREAD

**Issue by alexandrebedel** [alexandrebedel/SmartBin#29]
# Description

In order to "register" your new bin, you need to scan a QR code from the M5 screen providing a deep link with the binId which will open the mobile app and show your stats.

# Todo
- [x] Setup the binId on the FS
- [x] Display a QR code with the binId
- [x] Make sure the binId isn't overwritten by a refresh
