### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by alexandrebedel** [alexandrebedel/SmartBin#35]
# Description

The mobile needs to scan the QR code present on the M5, and then get the stats using the API

# Todo
- [x] Migrate expo project to typescript
- [x] Setup the deeplinking for the M5 qrcode
- [x] Improve the first load of the app to show a button if a bin id does not exist
- [ ] Mobile app styling
- [x] Make sure the bin id is saved after being scanned by the Camera plugin or the deep link
- [x] Get the stats using the binId
